import { createSidebarActions } from './sidebar-actions.js';
import { createSidebarRender } from './sidebar-render.js';
import { createSidebarBindings } from './sidebar-bindings.js';

export function buildUiRefs(documentRef = document) {
  return {
    modeToggle: documentRef.getElementById('mode-toggle'),
    bgToggle: documentRef.getElementById('bg-toggle'),
    bgImageSelect: documentRef.getElementById('bg-image-select'),
    bgImageUpload: documentRef.getElementById('bg-image-upload'),
    bgImageReset: documentRef.getElementById('bg-image-reset'),
    bgImageState: documentRef.getElementById('bg-image-state'),
    bgImageAlpha: documentRef.getElementById('bg-image-alpha'),
    bgVideoUpload: documentRef.getElementById('bg-video-upload'),
    bgVideoReset: documentRef.getElementById('bg-video-reset'),
    bgVideoState: documentRef.getElementById('bg-video-state'),
    bgVideoControls: documentRef.getElementById('bg-video-controls'),
    bgVideoPlayToggle: documentRef.getElementById('bg-video-play-toggle'),
    bgVideoProgress: documentRef.getElementById('bg-video-progress'),
    bgVideoAlpha: documentRef.getElementById('bg-video-alpha'),
    floatToggle: documentRef.getElementById('float-toggle'),
    alignBottomToggle: documentRef.getElementById('align-bottom-toggle'),
    frameGlassesToggle: documentRef.getElementById('frame-glasses-toggle'),
    framePhoneToggle: documentRef.getElementById('frame-phone-toggle'),
    phoneFrameControls: documentRef.getElementById('phone-frame-controls'),
    phoneFrameWidth: documentRef.getElementById('phone-frame-width'),
    phoneFrameHeight: documentRef.getElementById('phone-frame-height'),
    frameCornerRadius: documentRef.getElementById('frame-corner-radius'),
    phoneBgUpload: documentRef.getElementById('phone-bg-upload'),
    phoneBgReset: documentRef.getElementById('phone-bg-reset'),
    phoneBgState: documentRef.getElementById('phone-bg-state'),
    phoneBgVisibleToggle: documentRef.getElementById('phone-bg-visible-toggle'),
    phoneSceneVisibleRow: documentRef.getElementById('phone-scene-visible-row'),
    aiStageButtons: Array.from(documentRef.querySelectorAll('[data-ai-stage]')),
    scenarioList: documentRef.getElementById('scenario-list'),
    scenarioAdd: documentRef.getElementById('scenario-add'),
    scenarioDuplicate: documentRef.getElementById('scenario-duplicate'),
    scenarioDelete: documentRef.getElementById('scenario-delete'),
    stageAdd: documentRef.getElementById('stage-add'),
    stageAddKind: documentRef.getElementById('stage-add-kind'),
    stageDuplicate: documentRef.getElementById('stage-duplicate'),
    stageDelete: documentRef.getElementById('stage-delete'),
    stageRadiusInput: documentRef.getElementById('stage-radius-input'),
    stageRadiusVal: documentRef.getElementById('stage-radius-val'),
    stageWidthInput: documentRef.getElementById('stage-width-input'),
    stageWidthVal: documentRef.getElementById('stage-width-val'),
    stageHeightInput: documentRef.getElementById('stage-height-input'),
    stageHeightVal: documentRef.getElementById('stage-height-val'),
    stageImagePaddingField: documentRef.getElementById('stage-image-padding-field'),
    stageImagePaddingInput: documentRef.getElementById('stage-image-padding-input'),
    stageImagePaddingVal: documentRef.getElementById('stage-image-padding-val'),
    stageGapInput: documentRef.getElementById('stage-gap-input'),
    stageGapVal: documentRef.getElementById('stage-gap-val'),
    stageIconPadInput: documentRef.getElementById('stage-icon-pad-input'),
    stageIconPadVal: documentRef.getElementById('stage-icon-pad-val'),
    stageCardSRow: documentRef.getElementById('stage-card-s-row'),
    stageCardSToggle: documentRef.getElementById('stage-card-s-toggle'),
    stageListCountRow: documentRef.getElementById('stage-list-count-row'),
    stageListCountDec: documentRef.getElementById('stage-list-count-dec'),
    stageListCountVal: documentRef.getElementById('stage-list-count-val'),
    stageListCountInc: documentRef.getElementById('stage-list-count-inc'),
    stageListListeningOrbRow: documentRef.getElementById('stage-list-listening-orb-row'),
    stageListListeningOrbToggle: documentRef.getElementById('stage-list-listening-orb-toggle'),
    stageSelectedToggle: documentRef.getElementById('stage-selected-toggle'),
    stageShellHiddenToggle: documentRef.getElementById('stage-shell-hidden-toggle'),
    stageCelestialStyleSection: documentRef.getElementById('stage-celestial-style-section'),
    stageBlobTopCoreColor: documentRef.getElementById('stage-blob-top-core-color'),
    stageBlobTopEdgeColor: documentRef.getElementById('stage-blob-top-edge-color'),
    stageBlobBottomCoreColor: documentRef.getElementById('stage-blob-bottom-core-color'),
    stageBlobBottomEdgeColor: documentRef.getElementById('stage-blob-bottom-edge-color'),
    stageMaskBlurInput: documentRef.getElementById('stage-mask-blur-input'),
    stageMaskBlurVal: documentRef.getElementById('stage-mask-blur-val'),
    stageComponentsPanel: documentRef.getElementById('stage-components-panel'),
    stageComponentControls: documentRef.getElementById('stage-component-controls'),
    scenarioShapeRow: documentRef.getElementById('scenario-shape-row'),
    scenarioTriggers: documentRef.getElementById('scenario-triggers'),
    scenarioIconInput: documentRef.getElementById('scenario-icon-input'),
    scenarioIconUpload: documentRef.getElementById('scenario-icon-upload'),
    scenarioIconReset: documentRef.getElementById('scenario-icon-reset'),
    scenarioIconMode: documentRef.getElementById('scenario-icon-mode'),
    editorListItems: documentRef.getElementById('editor-list-items'),
    scenarioListItemsEditor: documentRef.getElementById('scenario-list-items-editor'),
    scenarioIconSize: documentRef.getElementById('scenario-icon-size'),
    scenarioIconColor: documentRef.getElementById('scenario-icon-color'),
    scenarioPrimary: documentRef.getElementById('scenario-primary'),
    scenarioPrimarySize: documentRef.getElementById('scenario-primary-size'),
    scenarioPrimaryColor: documentRef.getElementById('scenario-primary-color'),
    scenarioSecondary: documentRef.getElementById('scenario-secondary'),
    scenarioSecondarySize: documentRef.getElementById('scenario-secondary-size'),
    scenarioSecondaryColor: documentRef.getElementById('scenario-secondary-color'),
    scenarioDetail: documentRef.getElementById('scenario-detail'),
    scenarioDetailSize: documentRef.getElementById('scenario-detail-size'),
    scenarioDetailColor: documentRef.getElementById('scenario-detail-color'),
    editorActionCard: documentRef.getElementById('editor-action-card-field'),
    scenarioActionCardLeft: documentRef.getElementById('scenario-action-card-left'),
    scenarioActionCardRight: documentRef.getElementById('scenario-action-card-right'),
    actionCardPreviewText: documentRef.getElementById('layer-preview-action-card-text'),
    scenarioIntentHeader: documentRef.getElementById('scenario-intent-header'),
    scenarioIntentHeaderSize: documentRef.getElementById('scenario-intent-header-size'),
    scenarioIntentHeaderColor: documentRef.getElementById('scenario-intent-header-color'),
    scenarioMediaList: documentRef.getElementById('scenario-media-list'),
    editorIcon: documentRef.getElementById('editor-icon-layer'),
    editorPrimary: documentRef.getElementById('editor-primary-field'),
    editorSecondary: documentRef.getElementById('editor-secondary-field'),
    editorDetail: documentRef.getElementById('editor-detail-field'),
    editorIntentHeader: documentRef.getElementById('editor-intent-header-field'),
    editorMedia: documentRef.getElementById('editor-media-field'),
  };
}

export function initSidebar(context) {
  const refs = {};
  const ctx = {
    ...context,
    getScenarioLibrary: () => context.getScenarioLibrary(),
    setScenarioLibrary: (value) => context.setScenarioLibrary(value),
    getStageLibrary: () => context.getStageLibrary(),
    setStageLibrary: (value) => context.setStageLibrary(value),
    getSelectedScenarioId: () => context.getSelectedScenarioId(),
    setSelectedScenarioId: (value) => context.setSelectedScenarioId(value),
    getResponseMode: () => context.getResponseMode(),
    getAiStageOverride: () => context.getAiStageOverride(),
  };
  refs.actions = createSidebarActions(ctx, refs);
  refs.render = createSidebarRender(ctx, refs);
  refs.bindings = createSidebarBindings(ctx, refs);
  return { ...refs.actions, ...refs.render, ...refs.bindings };
}
